// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwpfe6H3ywG1yg21vlCMjcss60Au7kaw',
    appId: '1:818054283069:web:3083ca0a2f6d8b2a5b4f54',
    messagingSenderId: '818054283069',
    projectId: 'expensetracker-858d2',
    authDomain: 'expensetracker-858d2.firebaseapp.com',
    storageBucket: 'expensetracker-858d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXKoRm5go3H5ND9zi8Mkwxf-PuVw5bU7s',
    appId: '1:818054283069:android:ba87044fdaff6ccc5b4f54',
    messagingSenderId: '818054283069',
    projectId: 'expensetracker-858d2',
    storageBucket: 'expensetracker-858d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXDkb6IS3uCdwu2fluv6OKYWHuN2i0aU',
    appId: '1:818054283069:ios:d225b076afa20d845b4f54',
    messagingSenderId: '818054283069',
    projectId: 'expensetracker-858d2',
    storageBucket: 'expensetracker-858d2.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrXDkb6IS3uCdwu2fluv6OKYWHuN2i0aU',
    appId: '1:818054283069:ios:4f498f6e9ab279ff5b4f54',
    messagingSenderId: '818054283069',
    projectId: 'expensetracker-858d2',
    storageBucket: 'expensetracker-858d2.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
